# application.yml
spring:
  resources:
    cache:
      period: 0                 # Отключает кэширование статики
      cachecontrol:
        max-age: 0              # Указывает браузеру не кэшировать
  thymeleaf:
    cache: false                # Отключает кэширование шаблонов Thymeleaf
  devtools:
    livereload:
      enabled: true             # LiveReload сервер (на порту 35729)
    restart:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: StudyFriends
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/study_friends
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    generate-ddl: true

server:
  port: 8081
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
    path: /error.html
web:
  resources:
    add-mappings: false

